[project]
name = "cancer-rlto"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "mypy>=1.19.1",
    "pandas>=3.0.1",
    "ruff>=0.15.7",
    "scipy>=1.17.1",
]
authors = [
    { name="Abhinav Mishra", email="mishraabhinav36@gmail.com" },
]
